
spring:
  datasource:
    url: dioawsrdspostgresdb.cluster-ccv6crtbpnud.us-east-1.rds.amazonaws.com
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace