
spring:
  javax:
    persistence.jdbc.url: jdbc:postgresql://dioawsrdspostgresdb.cluster-ccv6crtbpnud.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: rootroot
  datasource:
    url: jdbc:postgresql://dioawsrdspostgresdb.cluster-ccv6crtbpnud.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        connection:
          url: jdbc:postgresql://dioawsrdspostgresdb.cluster-ccv6crtbpnud.us-east-1.rds.amazonaws.com:5432/postgres
          username: postgres
          password: rootroot

logging:
  level:
    org:
      hibernate:
        type: trace